language: python
python:
- 3.5

install:
  - pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl |cat
  - pip install torchvision | cat

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  #- hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION  h5py numpy scikit-image scipy
  - conda install pytorch torchvision -c soumith
  #- source activate test-environment


deploy:
  provider: pypi
  user: DerThorsten
  password:
    secure: !!binary |
      WlpNODE1V2oveEZOWHN0ZDczaVRkNzdrSnRQS0t6RjZQZTF0eXFzUEZVek5EeCtPNzVUcnVCZm4x
      OUl5aXRiZ1E4bEd4UWlTdEk3d3lRMTlBTkxTZkxsU3hpL1krdGVRSEZMaTBWc0xrVlU2RjRoZGho
      UVpEMVdOSnJsSm9SR3VrU1dnNGE2WjcrVE5CNUxwSXMwQjZ3Z0NiNXdvbU9QczdwcTh4ZklwZ2cr
      dlZJZjN6b0ZjVm1IVzFCd3hnb1BjNi94RVQxcnhVOCtxZU9ZcHRsckRCaGo2dnBMYVlSL0FDMk9C
      YUlGcEFUbEFZYnlONWlkU1haZUw4MTA4eEc4ZmhzcHhqcFdYekZuRVJQeUFNMnBjWEpTVlZ3L3d0
      MWZKemZ2U2JPVG93bkVxSDg2YmZidktBdy9Ta1B3djBpYnF3VkNqUHB6d0N2aEFlOUd0bG5UMnpm
      VXNEdVg5RHVzYkl0V0s3eENJVUhFcDU1UW8zenFjZWtmTDcxWktTdU0wN2xBSFpzVFo4a1RHZXk0
      UGV0S0ZMUFJFNVVyZHBqSjc3dE1GUWk5UFIzdjVrWDdCWGxMQVVLTjBHQWt0R0VuV2lCaFVCdHhx
      MkhYMHBFcnFXTTlVYTV3L3VUejMvV2lHamI3U3ZpRE9ETjBuZkcza2J4bi9IN0c3WDZ0WDhhYlFP
      MVMrSXJ1OTFMS3dMcHpsTlE1MTJLR2dXM0cxM25SRmJSS3lua2pxeWp2TUY2RkFGejAvS1lHeTBk
      N2ZZaTc1czNjYk10MW9TNlBCUEJWMXk2Q1c4bTFyaGpyODlVMmF4VVI1QThjZk9TM1NvTWZ2dkhw
      UDNORjBwM214cmRMd0ZKeCtTMEs2WDYwYkdoR3p3STlUY3N4RzlDZ2dBRXdxTlpBSGxPdDdSbTg9
  on:
    all_branches: false
    tags: true

script: 
  - source activate test-environment
  - python setup.py test
  - python setup.py install

# # This file was autogenerated and will overwrite each time you run travis_pypi_setup.py
# deploy:
#   true:
#     python: 3.5
#     repo: DerThorsten/inferno-1
#     tags: true
#   distributions: sdist bdist_wheel
#   password:
#     secure: !!binary |
#       cFJOVG9kNW0xNjExaWN2UVZWVGl5RVVjUlBBTnAzV2hoNDdPQUh4TUw3QUFVbDNQVWlCV09wZ3Iv
#       anRCcjNrVnVUY0RDTng5dEorNGpNUWhxakN4ZStadEo5Z3N2LytTeEdjUzk1WVFET2k5bHhxcTRX
#       UnlrbHd4V2t1UVkzV3NuRGh5d1ZOTUFrcTZWY0VaMEQzVmVVWkFSRDZ4ejRJYlZURlVqb01OaVNI
#       LzRKNFVZdmxlOUR0emFiTHBRUjBhUDhQTElIZGRHSVE0ditLZDk2Z3FSYnh0U0Npa01zOVZqWXE0
#       c0JiWmUzSy8yZDJXekV2U1JoN0NrWUthblZqclp6SzQ4bmYvcHVib2paS2wwNDYyU2JQM1RuTXh6
#       WTh6dHFWb3pZdjViM3FXOEVHYUd0czQzd3hNUkNTNmVOT3QwVk0ycERDdEhWaS9VRTlWTUdlRVln
#       ZytVYmJLTWhRellmZlRXNFdBbVVnbFlvSGwxb3poQ2JrZ3AzZEJWZkdTbFdBRmY2OFpGVFUxZTBN
#       eXJZQ0UrQkJLd29YNHA5MzNiTzc2NnhRN0F1TnlHaXRDU0VnRmw2Rmp4ME9LY3RBeHczSGE2dFVB
#       YVdUWVphd2tQaW9NajdTcVpxYXJQQzFIWmFod2FBbDBRVXpoU3dicW9QYm5zVGlaV2cvRW1HOXlJ
#       aXJxa2pSbjdOME9HTmg3N1k4N3ZlWjJQVVVLYTRxR2k4YXlNZW1WeEFCRmFXQklLU1Z2cGFnQ2ZI
#       TXRlcGxadXFGejNNeWdpQnV1S1lDNTJXK0d0Y0tITTV1YmNVTzN3aVFRRjZQdmFWaFVQNmVFN2pV
#       MXJyRE9Ja01oMXBpODhJSmdWL2NjU2RnOWZjdDdJcEpkZ0NQYzVxMGM2MGpYaklnWUczdkN6Sm89
#   user: DerThorsten
#   provider: pypi
# #install: 
# #  #- pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl 
# #  #- pip install torchvision
# #  - pip install --process-dependency-links  -U tox-travis
# language: python
# python:
# - 3.5
# #script: tox
