language: python
python:
- 3.5

install:
  - pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl 
  - pip install torchvision
  - pip install tox


deploy:
  provider: pypi
  user: DerThorsten
  password:
    secure: !!binary |
      eGI4TldHQ0x3b1RpRXRwbUlrcHRFWGR6eEIwS3d1QmVudnFRcFpNbC9EVHFuWDJhY0ZTNmEyWUl2
      MGU3SEpjdzRJZlErVGpTZVRicUJIekhYbFlvZVdtSWQzcmxzU3BOKzV0K0dRRFA4amVzSmlZNy90
      c1VLRjRZZjREa0hXclVNbTV2YkUxNDQwSnUyVkF4K0tSSlpJNXpNUTFEZmwyb3MrZFFRaFczc25q
      YUJ4MzVvZ3VnL3RFVlVTS0twVzd6ejdKOWFNbDFldUgvZmJkZlZ5N29LOHVKQmVKd2Z1TVdUZHBX
      UktGYi9VVVZLTnRNeTVjWEt6cWU3Zkh0Q3gxZ0dJRmd5eURlMTVyMGlBZUdaRkp3cWZUSkJxTWZX
      OG9yY2puYnVTZGZ4a2VYN0Jtc2tpSEc1dys5VDRZNzRpTjRuUm1ISFRkdmM1UHJSQXVzc2t1R2w2
      czhleWVRbUt3WmRvY1BSRzByT0NHYXJmYkhYcHFIS3lYOXNJL2ZCUUxMSlRHeUpRT045eXZvbGkz
      YUg3UU43ZWE0SS9ZNS92eDZmNDBMR2xKclVGbHFtUld6MWRKRUplWG5ZNnBaVThNVXE4eXdlRkJu
      TnhNanVHRU1wWi8xOHNneTlqTXNVaVJYZDU2Q3piUXhOT2JaUUUrWFlrOWk3M2gva3RZZnVFcytT
      bmNvMHo1Nmpla3NWVkt0aGRaVXA3OUx4TWFCRlpJSDFjU1liVzFWVFFpYVRvR01nMnlSN2ZMSVE4
      cWNmUHk3Ukh3eEROd3VPWElUV3ZEb2djMkdORkxwNkt2Z21IaHpXR2xnOVJLalhTZVM0QzRqR3Bh
      dzBSOUhoYW1XMVlRcGhMRGxGd1VGUmdFSU1VdVFrRVNBVDBtT3FPQmhYN2pBNXdQMlZjMjVIS3c9
  on:
    all_branches: true


script: echo "a"


# # This file was autogenerated and will overwrite each time you run travis_pypi_setup.py
# deploy:
#   true:
#     python: 3.5
#     repo: DerThorsten/inferno-1
#     tags: true
#   distributions: sdist bdist_wheel
#   password:
#     secure: !!binary |
#       cFJOVG9kNW0xNjExaWN2UVZWVGl5RVVjUlBBTnAzV2hoNDdPQUh4TUw3QUFVbDNQVWlCV09wZ3Iv
#       anRCcjNrVnVUY0RDTng5dEorNGpNUWhxakN4ZStadEo5Z3N2LytTeEdjUzk1WVFET2k5bHhxcTRX
#       UnlrbHd4V2t1UVkzV3NuRGh5d1ZOTUFrcTZWY0VaMEQzVmVVWkFSRDZ4ejRJYlZURlVqb01OaVNI
#       LzRKNFVZdmxlOUR0emFiTHBRUjBhUDhQTElIZGRHSVE0ditLZDk2Z3FSYnh0U0Npa01zOVZqWXE0
#       c0JiWmUzSy8yZDJXekV2U1JoN0NrWUthblZqclp6SzQ4bmYvcHVib2paS2wwNDYyU2JQM1RuTXh6
#       WTh6dHFWb3pZdjViM3FXOEVHYUd0czQzd3hNUkNTNmVOT3QwVk0ycERDdEhWaS9VRTlWTUdlRVln
#       ZytVYmJLTWhRellmZlRXNFdBbVVnbFlvSGwxb3poQ2JrZ3AzZEJWZkdTbFdBRmY2OFpGVFUxZTBN
#       eXJZQ0UrQkJLd29YNHA5MzNiTzc2NnhRN0F1TnlHaXRDU0VnRmw2Rmp4ME9LY3RBeHczSGE2dFVB
#       YVdUWVphd2tQaW9NajdTcVpxYXJQQzFIWmFod2FBbDBRVXpoU3dicW9QYm5zVGlaV2cvRW1HOXlJ
#       aXJxa2pSbjdOME9HTmg3N1k4N3ZlWjJQVVVLYTRxR2k4YXlNZW1WeEFCRmFXQklLU1Z2cGFnQ2ZI
#       TXRlcGxadXFGejNNeWdpQnV1S1lDNTJXK0d0Y0tITTV1YmNVTzN3aVFRRjZQdmFWaFVQNmVFN2pV
#       MXJyRE9Ja01oMXBpODhJSmdWL2NjU2RnOWZjdDdJcEpkZ0NQYzVxMGM2MGpYaklnWUczdkN6Sm89
#   user: DerThorsten
#   provider: pypi
# #install: 
# #  #- pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl 
# #  #- pip install torchvision
# #  - pip install --process-dependency-links  -U tox-travis
# language: python
# python:
# - 3.5
# #script: tox
