language: python
python:
- 3.5

# install:
#   - pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl 
#   - pip install torchvision
#   - pip install tox


deploy:
  provider: pypi
  user: DerThorsten
  password:
    secure: !!binary |
      cThCWlRhWU5zL1RyejBhMnZXTW42R1VGTGFMLzRTc0NvTlEvM21heFIwdHRiMTdwblltaTVsN3Ny
      ejY2QUdNa1NVVnhGd2U5eGYvVngzajhhRXlyazE0L3lDemFleSszVmN4UFdCTW5KQmV0UWhqQVVl
      TnZlUkpVVFA3aVk5M0xSWWdHOEp0NDg5d0VDUHdHdW1TblZXS0FxZ012S0tzRU1hMGZPK0dOdStD
      eXoyS2FmQjdYVTFNUTg5YzVNMXBjazM4d1RkQlRGTlNVMFl0aVZGcjNFOWU5Tk5MMit0U0RKOUE5
      UXpQak5PeHpiTXlLYzVqalBCMkxHVHJMMHR2Nmt1eFZzSjNuVjNrZUltblk0U1hDQ3ZxeGlPelYr
      ckQ2RXNCVExvU0U2QTc1bWN3QWd3TzBHempqWUZaMi94THp2N1UySENkVFp2MnJ6V3FiMG11VnJ2
      Z1BQVm5QOTR5R1NGQVJsbWorMG92ajFKWk1iTnRrK1NMekY1U0hHQ2lxN3RXK0x6bTc5cHB4emJy
      ZDV6SmlnMlc3bSs4b1IybCtaT2dWcVM3TVFabEI4OFM4ak5JcmpRTktidVM0cTk0ZzRhVnRwTnhF
      S25UQUdaNVQ3K1YzK1cxaHU4UUc2bEFtVDJaZGYvYTJuRVR6MGNxcWNaZWdGcDVUaU8vcU1YaVFp
      akx2MmhkREx2K2NTRkszdHB5OVhIcmNyMGlJRHVHRS9SUUFYcitjaVByQ2twR3Z5VDI3T0t4OWUy
      S0ZrNHFOL0NVZFQvYVZhR3BLZFJmallZY3pKU2paVEJqVGMzZFNrblp2Mkp1RUVHL0RUTERFblNX
      anZEWit2UnN5SjBmTXhvay9RV0VnKzAyR3h2WDQ2NTlQQnkzZEl6Qm5tS05oNE1Rc0Y4V3VWZ0k9
  on:
    all_branches: true


script: echo "a"


# # This file was autogenerated and will overwrite each time you run travis_pypi_setup.py
# deploy:
#   true:
#     python: 3.5
#     repo: DerThorsten/inferno-1
#     tags: true
#   distributions: sdist bdist_wheel
#   password:
#     secure: !!binary |
#       cFJOVG9kNW0xNjExaWN2UVZWVGl5RVVjUlBBTnAzV2hoNDdPQUh4TUw3QUFVbDNQVWlCV09wZ3Iv
#       anRCcjNrVnVUY0RDTng5dEorNGpNUWhxakN4ZStadEo5Z3N2LytTeEdjUzk1WVFET2k5bHhxcTRX
#       UnlrbHd4V2t1UVkzV3NuRGh5d1ZOTUFrcTZWY0VaMEQzVmVVWkFSRDZ4ejRJYlZURlVqb01OaVNI
#       LzRKNFVZdmxlOUR0emFiTHBRUjBhUDhQTElIZGRHSVE0ditLZDk2Z3FSYnh0U0Npa01zOVZqWXE0
#       c0JiWmUzSy8yZDJXekV2U1JoN0NrWUthblZqclp6SzQ4bmYvcHVib2paS2wwNDYyU2JQM1RuTXh6
#       WTh6dHFWb3pZdjViM3FXOEVHYUd0czQzd3hNUkNTNmVOT3QwVk0ycERDdEhWaS9VRTlWTUdlRVln
#       ZytVYmJLTWhRellmZlRXNFdBbVVnbFlvSGwxb3poQ2JrZ3AzZEJWZkdTbFdBRmY2OFpGVFUxZTBN
#       eXJZQ0UrQkJLd29YNHA5MzNiTzc2NnhRN0F1TnlHaXRDU0VnRmw2Rmp4ME9LY3RBeHczSGE2dFVB
#       YVdUWVphd2tQaW9NajdTcVpxYXJQQzFIWmFod2FBbDBRVXpoU3dicW9QYm5zVGlaV2cvRW1HOXlJ
#       aXJxa2pSbjdOME9HTmg3N1k4N3ZlWjJQVVVLYTRxR2k4YXlNZW1WeEFCRmFXQklLU1Z2cGFnQ2ZI
#       TXRlcGxadXFGejNNeWdpQnV1S1lDNTJXK0d0Y0tITTV1YmNVTzN3aVFRRjZQdmFWaFVQNmVFN2pV
#       MXJyRE9Ja01oMXBpODhJSmdWL2NjU2RnOWZjdDdJcEpkZ0NQYzVxMGM2MGpYaklnWUczdkN6Sm89
#   user: DerThorsten
#   provider: pypi
# #install: 
# #  #- pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl 
# #  #- pip install torchvision
# #  - pip install --process-dependency-links  -U tox-travis
# language: python
# python:
# - 3.5
# #script: tox
