language: python
python:
- 3.5

install:


  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  #- hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION  h5py numpy scikit-image scipy
  - conda install pytorch torchvision -c soumith
  - conda install -c anaconda pyyaml 
  - source activate test-environment


deploy:
  provider: pypi
  user: DerThorsten
  password:
    secure: !!binary |
      Y2JQUUl5d2tOQ01JRG8xY0RTYmpyVVdvYmEyWGpZMG9qOXU5M2tQL01XTkJPUmpIZ2VHem9EN0lW
      Tmh2aU83U2NmRWozTld0K2hRdEpZWnRhSStOWFdjWUZuVFU1WWs1WmdlS2IvRCs5Y0tHbHcvWkIv
      QS8yaWJDQmp3TGdLUVg5RFduU3p4dncrWFBJTFZJMlFudkFJNkFnRHFHZnJrR0JEdHRqa0J1akJp
      RG5wQWFJOWljVVJtS3NwY3VZQ3cvWVFEcXQySGQwY1ZrcGRwOTR0eWROYjlDa2RWbG9DUU96U0VW
      OXpQamNEaDg1d2lOMUNzdldDV1R5aEd1WWRBVHdySGVBbE9KWmJtSjl2UDBZQjc1REdRdTRIMEY1
      TE5RMzZkY1Uzb0t2VU9LOEtvaHMwSFdaZkNTU05VVnlIdktLOGxUUE1aOGJUcXllUUw5SFc2c2dy
      YTR6OEM4WlJ1dDBFeDdvekVHNXdHNGRlSmVDeDFidWFtUDkzdm9OSVJlbSsvbHI2QmRueVhRd0w2
      eWZCODVPSVlaMGltdDN5SFk4RllqYkhwbDhSdVpmajlYazU4QTVoQituOE9pbyt6OE9tZFh4ZWk0
      SmZJM01rbjdRY0hTa01kREV0ZHJIc2FxeU1DMjBaeDJUTDY5L1A1MzN3emlwVDU1Nm9Wc0lxd1VR
      UFdaYlNSTWJMdkxYK2pzMjNIWnQ1TzZJaUt0WDl6ODlqUDlWNFpNYlliY0hmWXB6emd5dVRrY3dL
      Ulh1QW4yWHF4RHo0c2hTOTdZbUNGYmdram5XZE5MYVkzZk96NnNBWjBJOExGODR0Z05XN281SzJJ
      R2hSZDhrcTdVS1NpbCs3d2hEbEtwcVpuOUp1bDJpK3FsdDBkVEVkV2duRlBnWDQ3OWJCUzV3SVk9
  on:
    all_branches: false
    tags: true

script: 
  - source activate test-environment
  - pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl |cat
  - pip install torchvision | cat
  - pip install pytest | cat
  - pip install dill
  - pytest tests/test_inferno.py
  - python setup.py install

# # This file was autogenerated and will overwrite each time you run travis_pypi_setup.py
# deploy:
#   true:
#     python: 3.5
#     repo: DerThorsten/inferno-1
#     tags: true
#   distributions: sdist bdist_wheel
#   password:
#     secure: !!binary |
#       cFJOVG9kNW0xNjExaWN2UVZWVGl5RVVjUlBBTnAzV2hoNDdPQUh4TUw3QUFVbDNQVWlCV09wZ3Iv
#       anRCcjNrVnVUY0RDTng5dEorNGpNUWhxakN4ZStadEo5Z3N2LytTeEdjUzk1WVFET2k5bHhxcTRX
#       UnlrbHd4V2t1UVkzV3NuRGh5d1ZOTUFrcTZWY0VaMEQzVmVVWkFSRDZ4ejRJYlZURlVqb01OaVNI
#       LzRKNFVZdmxlOUR0emFiTHBRUjBhUDhQTElIZGRHSVE0ditLZDk2Z3FSYnh0U0Npa01zOVZqWXE0
#       c0JiWmUzSy8yZDJXekV2U1JoN0NrWUthblZqclp6SzQ4bmYvcHVib2paS2wwNDYyU2JQM1RuTXh6
#       WTh6dHFWb3pZdjViM3FXOEVHYUd0czQzd3hNUkNTNmVOT3QwVk0ycERDdEhWaS9VRTlWTUdlRVln
#       ZytVYmJLTWhRellmZlRXNFdBbVVnbFlvSGwxb3poQ2JrZ3AzZEJWZkdTbFdBRmY2OFpGVFUxZTBN
#       eXJZQ0UrQkJLd29YNHA5MzNiTzc2NnhRN0F1TnlHaXRDU0VnRmw2Rmp4ME9LY3RBeHczSGE2dFVB
#       YVdUWVphd2tQaW9NajdTcVpxYXJQQzFIWmFod2FBbDBRVXpoU3dicW9QYm5zVGlaV2cvRW1HOXlJ
#       aXJxa2pSbjdOME9HTmg3N1k4N3ZlWjJQVVVLYTRxR2k4YXlNZW1WeEFCRmFXQklLU1Z2cGFnQ2ZI
#       TXRlcGxadXFGejNNeWdpQnV1S1lDNTJXK0d0Y0tITTV1YmNVTzN3aVFRRjZQdmFWaFVQNmVFN2pV
#       MXJyRE9Ja01oMXBpODhJSmdWL2NjU2RnOWZjdDdJcEpkZ0NQYzVxMGM2MGpYaklnWUczdkN6Sm89
#   user: DerThorsten
#   provider: pypi
# #install: 
# #  #- pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl 
# #  #- pip install torchvision
# #  - pip install --process-dependency-links  -U tox-travis
# language: python
# python:
# - 3.5
# #script: tox
